package rqmcexperiments;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Runs the NUS all-methods timing-analysis reporting workflow.
 *
 * <p>This runner reads the CSV files produced by the NUS timing and regression
 * experiments, writes clearly named summary CSV files, and saves the plots used
 * to inspect the timing behavior of all methods.
 */
public class AllMethodsNusTimeAnalysis {

   /**
    * Executes the full NUS timing-analysis workflow and writes all reports.
    */
   public static void main(String[] args) throws IOException {
      // The run count selects the matching timing and regression result files.
      int runs = 11;

      // The timing plot focuses on how median execution time changes with m
      // when the dimension s and sample-size exponent k are fixed.
      int timePlotS = 32;
      int timePlotK = 16;

      String resDir = "/home/otman/Documents/GitHub/rqmc-experiments/";

      // The input directory contains the raw all-methods timing table and the
      // regression outputs generated by AllmethodsNusRegCsv.
      Path inputDirectory = Path.of(resDir+"data/");

      // The output directory receives every summary CSV, PNG plot, and LaTeX
      // plot produced by this timing-analysis script.
      Path outputDirectory = Path.of(
            resDir + "plots/");
      Files.createDirectories(outputDirectory);

      // Detailed input tables used by the summaries and plots below.
      Path interactionRBetaGridInput = inputDirectory.resolve(
            "interaction-r-beta-grid-r" + runs + ".csv");
      Path interactionRegressionCoefficientsInput = inputDirectory.resolve(
            "interaction-regression-coefficients-r" + runs + ".csv");
      Path allMethodsTimingInput = inputDirectory.resolve(
            "allMetTime" + runs + ".csv");

      // Summary CSV: median and quartiles of interaction-based r_beta grouped
      // by method and by m. This shows how the relative m effect changes as the
      // number of replications grows.
      Path medianRBetaByMSummary = outputDirectory.resolve(
            "median-r-beta-by-m-from-interaction-model-summary-r"
                  + runs + ".csv");
      TimingAnalysisPlots.writeRBetaSummary(
            interactionRBetaGridInput, medianRBetaByMSummary, "m");

      // Summary CSV: median and quartiles of interaction-based r_beta grouped
      // by method and by k. This shows how the relative m effect changes as
      // n = 2^k grows.
      Path medianRBetaByKSummary = outputDirectory.resolve(
            "median-r-beta-by-k-from-interaction-model-summary-r"
                  + runs + ".csv");
      TimingAnalysisPlots.writeRBetaSummary(
            interactionRBetaGridInput, medianRBetaByKSummary, "k");

      // Summary CSV: coefficient_mn / s by method. This estimates repeated
      // cost per point, per replication, and per dimension from the fitted
      // interaction coefficient.
      Path repeatedCostPerPointPerReplicationPerDimensionSummary =
            outputDirectory.resolve(
                  "repeated-cost-per-point-per-replication-per-dimension"
                        + "-from-interaction-coefficients-summary-r"
                        + runs + ".csv");
      TimingAnalysisPlots.writeInteractionRatioSummary(
            interactionRegressionCoefficientsInput,
            repeatedCostPerPointPerReplicationPerDimensionSummary, true);

      // Summary CSV: coefficient_n / coefficient_mn by method. This compares
      // the n-dependent cost to the repeated m*n cost in the interaction model.
      Path nDependentCostToRepeatedCostRatioSummary = outputDirectory.resolve(
            "n-dependent-cost-to-repeated-cost-ratio"
                  + "-from-interaction-coefficients-summary-r"
                  + runs + ".csv");
      TimingAnalysisPlots.writeInteractionRatioSummary(
            interactionRegressionCoefficientsInput,
            nDependentCostToRepeatedCostRatioSummary, false);

      // Summary CSV: median execution time by method and m at one fixed s and
      // k. This is the compact table used to plot execution time versus m.
      Path medianExecutionTimeByMSummary = outputDirectory.resolve(
            "median-execution-time-by-m-for-s" + timePlotS
                  + "-k" + timePlotK + "-summary-r" + runs + ".csv");
      TimingAnalysisPlots.writeTimeSummary(
            allMethodsTimingInput, medianExecutionTimeByMSummary,
            timePlotS, timePlotK);

      // Plot: median interaction-based r_beta versus m, with one line per
      // method and a reference line at r_beta = 1.
      TimingAnalysisPlots.saveRBetaPlot(
            medianRBetaByMSummary, "m", "Number of replications m",
            "Median interaction-based r_beta versus m",
            outputDirectory.resolve(
                  "median-r-beta-by-m-from-interaction-model-r"
                        + runs + ".png"));

      // Plot: median interaction-based r_beta versus k, where n = 2^k, with
      // one line per method and a reference line at r_beta = 1.
      TimingAnalysisPlots.saveRBetaPlot(
            medianRBetaByKSummary, "k", "k (n = 2^k)",
            "Median interaction-based r_beta versus k",
            outputDirectory.resolve(
                  "median-r-beta-by-k-from-interaction-model-r"
                        + runs + ".png"));

      // Plot: min-to-max range, interquartile range, and median of
      // coefficient_mn / s for each method. The horizontal axis is logarithmic
      // because this repeated-cost quantity can span several scales.
      TimingAnalysisPlots.saveHorizontalComparison(
            repeatedCostPerPointPerReplicationPerDimensionSummary, true,
            "Repeated cost per point, per replication, and per dimension",
            "coefficient_mn / s",
            outputDirectory.resolve(
                  "repeated-cost-per-point-per-replication-per-dimension"
                        + "-by-method-r" + runs + ".png"));

      // Plot: min-to-max range, interquartile range, and median of
      // coefficient_n / coefficient_mn for each method. This compares the
      // n-dependent term against the repeated interaction term.
      TimingAnalysisPlots.saveHorizontalComparison(
            nDependentCostToRepeatedCostRatioSummary, false,
            "n-dependent cost to repeated cost ratio",
            "coefficient_n / coefficient_mn",
            outputDirectory.resolve(
                  "n-dependent-cost-to-repeated-cost-ratio-by-method-r"
                        + runs + ".png"));

      // Plot: median execution time versus m for the selected s and k. The PNG
      // is convenient for reports, and the LaTeX file can be included in papers
      // or generated documentation.
      TimingAnalysisPlots.saveTimePlot(
            medianExecutionTimeByMSummary, timePlotS, timePlotK,
            outputDirectory.resolve(
                  "median-execution-time-by-m-for-s" + timePlotS
                        + "-k" + timePlotK + "-r" + runs + ".png"),
            outputDirectory.resolve(
                  "median-execution-time-by-m-for-s" + timePlotS
                        + "-k" + timePlotK + "-r" + runs + ".tex"));
   }
}
