/*
 * Class:        DigitalNetBase2
 * Description:
 * Environment:  Java
 * Software:     SSJ
 * Copyright (C) 2001  Pierre L'Ecuyer and Universite de Montreal
 * Organization: DIRO, Universite de Montreal
 * @author
 * @since
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package umontreal.ssj.hups64;

import java.util.Arrays;

import umontreal.ssj.rng.*;
import umontreal.ssj.util.*;

/**
 * A special case of @ref DigitalNet for the base @f$b=2@f$. The implementation
 * exploit the binary nature of computers and is much more efficient than for
 * the case of a general @f$b=2@f$. Binary expansions are easy to obtain because
 * the computer already uses them internally. The generator
 * matrices @f$\mathbf{C}_j@f$ are stored in a single large array of
 * size @f$sk@f$. The @f$c@f$-th column of @f$\mathbf{C}_j@f$,
 * for @f$c=0,\dots,k-1@f$, is stored at position @f$jk + c@f$ of this array, as
 * a 64-bit (long) integer, whose value must be less than @f$2^w@f$, where @f$k\le w \le 63@f$.
 * The @f$w@f$ least-significant bits of this integer are the entries of that column.
 * The least signifiant bit is the entry of row @f$w-1@f$, the second least significant
 * is the entry of row @f$w-2@f$, etc., and the most significant bit (which can be zero)
 * is the entry in row 0.  Often, we know that only the first @f$r < w@f$ rows of
 * the matrix are non-zero. For example, for the original Sobol points, we have @f$r=k@f$.
 * In that case, the integer that represents the column will be a multiple of @f$2^{w-r}@f$.
 * The values of @f$w@f$ cannot exceed 63 (64 is not allowed
 * because Java does not have 64-bit unsigned integers). 
 * In this class, the random digital shift in base 2 generated by
 * `addRandomShift` corresponds to a random XOR.
 * 
 * <div class="SSJ-bigskip"></div><div class="SSJ-bigskip"></div>
 */
public class DigitalNetBase2Test extends DigitalNet {
   private transient long[] originalMat; // Original matrices, without randomization.
   protected long[] genMat; // The current generator matrix.
   protected transient long[] digitalShift; // Stores the digital shift vector.

   
   // Stream used to add independent random bits beyond the first `k` bits, for all the points.
   RandomStream streamIRB;  // Used to generate `outputDigits - k` random bits for each coordinate.
   
   
   // These are used to store deterministic information for NUS.
   protected RandomStream streamNUS; // Stream used for NUS.
   protected double normFactorNUS;   // Normalization used for NUS.
   protected int numBitsNUS;         // Number of bits randomized by NUS.
   protected int[][] poslistNUS;     //  = new int[2 * numPoints][dim];
   protected int[][] poslistInvNUS;  //  = new int[numPoints][dim];
   protected long[][] bvlistNUS;     //  = new long[2 * numPoints][dim];

   /**
    * Returns the generator matrices in the natural format, which is a
    * 3-dimensional array of shape dim x numRows x numCols. This format uses an int
    * for each bit, so this is slow and takes much memory!
    */
   public long[][][] generatorMatricesToBitFormat() {
      int r, c, j; // Row r, column c, dimension j.
      long[][][] bitMatrices = new long[dim][numRows][numCols];
      for (j = 0; j < dim; j++) {
         for (c = 0; c < numCols; c++) {
            long column = genMat[j * numCols + c]; // This column as an integer.
            column >>= outDigits - numRows; // outDigits (or w) is used here.
            for (r = numRows - 1; r >= 0; r--) {
               bitMatrices[j][r][c] = (column & 1L);
               column >>= 1;
            }
         }
      }
      return bitMatrices;
   }

   /**
    * Sets the generator matrices from matrices in the standard format. Standard
    * format is a 3-dimensional array of shape dimension x number of rows x number
    * of columns.
    */
   public void generatorMatricesFromBitFormat(long[][][] bitMatrices) {
      assert bitMatrices.length == dim;
      assert bitMatrices.length > 0;
      assert bitMatrices[0].length == numRows;
      assert bitMatrices[0].length > 0;
      assert bitMatrices[0][0].length == numCols;

      genMat = new long[dim * numCols];
      int r, c, j; // Row r, column c, dimension j.
      for (j = 0; j < dim; ++j) {
         for (r = 0; r < numRows; ++r) {
            for (c = 0; c < numCols; ++c) {
               genMat[j * numCols + c] += bitMatrices[j][r][c] * (1L << (outDigits - 1 - r));
            }
         }
      }
   }

   /**
    * Prints the generator matrices as binary matrices in their standard form,
    * for dimensions 1 to @f$s@f$. Each binary matrix has @f$r@f$ rows and @f$k@f$ columns.
    */
   public void printGeneratorMatricesBits(int s) {
      int r, c, j; // Row r, column c, dimension j.
      long[][][] standardMatrices = generatorMatricesToBitFormat();
      for (j = 0; j < s; j++) {
         System.out.println("dim = " + (j + 1) + PrintfFormat.NEWLINE);
         for (r = 0; r < numRows; r++) {
            StringBuffer sb = new StringBuffer();
            for (c = 0; c < numCols; c++) {
               sb.append(standardMatrices[j][r][c]);
            }
            System.out.println(sb);
         }
         System.out.println("----------------------------------");
      }
   }

   /**
    * Prints all the columns of the generator matrices in the form of integers 
    * per column, for dimensions 1 to @f$s@f$.
    */
   public void printGeneratorMatricesColumns(int s) {
      // column c, dimension j.
      for (int j = 0; j < s; j++) {
         System.out.println("dim = " + (j + 1) + PrintfFormat.NEWLINE);
         for (int c = 0; c < numCols; c++)
            System.out.println(genMat[j * numCols + c]);
         System.out.println("----------------------------------");
      }
   }

   /**
    * Returns a copy of the generator matrices transposed in the form of integers
    * for dimensions 1 to @f$s@f$. Each integer corresponds to one column of bits.
    */
   public long[] getGeneratorMatricesColumns() {
      return Arrays.copyOf(genMat, genMat.length);
   }

   public double getCoordinate(int i, int j) {
      long res;
      int pos = 0;
      int grayCode = i ^ (i >> 1);

      if (digitalShift == null)
         res = 0;
      else
         res = digitalShift[j];
      while ((grayCode >> pos) != 0) {
         if (((grayCode >> pos) & 1) != 0)
            res ^= genMat[j * numCols + pos];
         pos++;
      }
      if (digitalShift != null)
         return res * normFactor + EpsilonHalf;
      else
         return res * normFactor;
   }

   public double getCoordinateNoGray(int i, int j) {
      long res;
      if (digitalShift == null)
         res = 0;
      else
         res = digitalShift[j];
      int pos = 0; // Position of the bit that is examined.
      // Add (xor) the columns of C_j for which the corresponding bit of i is 1.
      // Least significant bit of i goes with first column of C_j.
      // The first row of C_j is for the most significant bit of output, u_{i,j,1}.
      while ((i >> pos) != 0) {
         if ((((i >> pos) & 1) != 0) && (pos < numCols))
            res ^= genMat[j * numCols + pos];
         pos++;
      }
      if (digitalShift != null)
         // This EpsilonHalf must be explained in the doc.
         // It prevents the output of 0.
         // normFactor is 2^{-outDigits}.
         return res * normFactor + EpsilonHalf;
      else
         return res * normFactor;
   }

   /**
    * Returns a `DigitalNetBase2Iterator` which enumerates the points using a Gray
    * code.
    */
   public PointSetIterator iterator() {
      return new DigitalNetBase2Iterator();
   }

   /**
    * This iterator does not use the Gray code. Thus the points are enumerated in
    * the order of their first coordinate before randomization.
    */
   public PointSetIterator iteratorNoGray() {
      return new DigitalNetBase2IteratorNoGray();
   }

   public String toString() {
      StringBuffer sb = new StringBuffer("DigitalNetBase2: ");
      sb.append(super.toString());
      return sb.toString();
   }

   public void addRandomShift(int d1, int d2, RandomStream stream) {
      if (null == stream)
         throw new IllegalArgumentException(PrintfFormat.NEWLINE + "   Calling addRandomShift with null stream");
      if (0 == d2)
         d2 = Math.max(1, dim);
      if (digitalShift == null) {
         digitalShift = new long[d2];
         capacityShift = d2;
      } else if (d2 > capacityShift) {
         int d3 = Math.max(4, capacityShift);
         while (d2 > d3)
            d3 *= 2;
         long[] temp = new long[d3];
         capacityShift = d3;
         for (int i = 0; i < d1; i++)
            temp[i] = digitalShift[i];
         digitalShift = temp;
      }
      long maxj;
      if (outDigits < 63) // outDigit (= w) is used here for the digital shift!
         maxj = (1L << outDigits) - 1;
      else
         maxj = (1L << 63) - 1;   // (long) 9223372036854775807;   // 2^{63}-1
      for (int i = d1; i < d2; i++)
         digitalShift[i] = stream.nextLong(0, maxj);     //  ***************
      dimShift = d2;
      shiftStream = stream;
   }

   public void addRandomShift(RandomStream stream) {
      addRandomShift(0, dim, stream);
   }


   public void clearRandomShift() {
      super.clearRandomShift();
      digitalShift = null;
   }

   
   /**
    * After setting this, each iterator will add `outDigits - k` independent random bits
    * after the first `k` bits of each coordinate of each point.
    * Note that NUS already does this by default. We can do it for other methods as well.
    */   
   public void addIndepRandomBits(RandomStream stream) {
      streamIRB = stream;
   }


   public void clearIndepRandomBits() {
      streamIRB = null;
   }
    
   
   // Left-multiplies lower-triangular matrix Mj by original C_j,
   // where original C_j is in originalMat and result is in genMat.
   // Mj[d] is assumed to contain the d-th subdiagonal of matrix Mj,
   // for d=0,...,w-1. Each subdiagonal is represented as a
   // w-bit integer, whose most significant bits are those on the
   // diagonal. For example, for d=w-3, the subdiagonal has 3 bits,
   // say b1, b2, b3, and is represented by the integer
   // Mj[w-3] = b1 * 2^{w-1} + b2 * 2^{w-2} + b3 * b^{w-3}.
   //
   private void leftMultiplyMat(int j, long[] Mj) {
      int c, d;  // Dimension j      
      long col;  // column c for new C_j.
      for (c = 0; c < numCols; c++) {
         col = 0;
         for (d = 0; d < outDigits; d++)
            // Multiply subdiagonal d of M_j by column c of C_j, and xor.
            col ^= (Mj[d] & originalMat[j * numCols + c]) >> d;
         genMat[j * numCols + c] = col;
      }
   }

   /*
    * // Left-multiplies lower-triangular matrix Mj by original C_j, // where
    * original C_j is in originalMat and result is in genMat. private void
    * leftMultiplyMat (int j, int[] Mj) { int c, l, i, prod; // Dimension j, column
    * c for new C_j. int numOnes; int col; // Will be column c of genMat. for (c =
    * 0; c < numCols; c++) { col = 0; for (l = 0; l < outDigits; l++) { // Multiply
    * row l of M_j by column c of C_j. prod = Mj[l] & originalMat[j* numCols + c];
    * numOnes = 0; // Counts the number of ones in prod, modulo 2. for (i = 0; i <
    * outDigits; i++) numOnes += (1 & prod >> i); // Put a 1 in column c, row l, of
    * C_j if numOnes is odd. col += ((numOnes & 1) << (outDigits-l-1)); } genMat[j
    * * numCols + c] = col; } }
    */

   // Right-multiplies upper-triangular matrix Mj by original C_j,
   // where original C_j is in originalMat and result is in genMat.
   // Mj[d] is assumed to contain the d-th column of matrix Mj,
   // for d=0,...,w-1. Each column is represented as a w-bit integer,
   // whose most significant bits are those at index 0.
   // For example, for d=2, the column has 3 bits, (the others are 0
   // since under the diagonal) say b1, b2, b3, and is represented by
   // the integer Mj[2] = b1 * 2^{w-1} + b2 * 2^{w-2} + b3 * b^{w-3}.
   //
   private void rightMultiplyMat(int j, long[] Mj) {
      int c, r;  // Dimension j
      long col;  // column c for new C_j.
      long mask;  // Bit of column Mj[c]

      for (c = 0; c < numCols; c++) {
         mask = (long)1 << outDigits - 1;
         col = originalMat[j * numCols + c];
         for (r = 0; r < c; r++) {
            // If bit (outDigits - 1 - r) of Mj[c] is 1, add column r
            if ((Mj[c] & mask) != 0)
               col ^= originalMat[j * numCols + r];
            mask >>= 1;
         }
         genMat[j * numCols + c] = col;
      }
   }

   /*
    * // Right-multiplies original C_j by upper-triangular matrix Mj, // where
    * original C_j is in originalMat and result is in genMat. private void
    * rightMultiplyMat (int j, long[] Mj) { int c, l, i, mask; // Dimension j,
    * column c for new C_j. int numOnes; int col; // Will be column c of genMat.
    * boolean bool1, bool2; for (c = 0; c < numCols; c++) { col = 0; for (l = 0; l
    * < outDigits; l++) { // Multiply row l of C_j by column c of Mj. mask = (1 <<
    * outDigits-l-1); // ??? // xor = originalMat[j* numCols + l] & Mj[c]; numOnes
    * = 0; // Counts the number of ones in xor, modulo 2. for (i = 0; i < numCols;
    * i++) { bool1 = (mask & originalMat[j * numCols + i]) != 0; bool2 = ((1 <<
    * (outDigits-i-1)) & Mj[i]) != 0; if (bool1 & bool2) numOnes++; } // Put a 1 in
    * column c, row l, of C_j if numOnes is odd. col += ((numOnes & 1) <<
    * (outDigits-l-1)); } genMat[j * numCols + c] = col; } }
    */

   /** This is a version of LMS in which each column of the lower-triangular 
    * scrambling matrix is represented as an integer less than `2^w`, just like for Cj.
    * The nonzero part of L_j will be `r x numRows` with `r = numBits <= outDigits`, 
    * so the scrambled generating matrices will have `r` nonzero rows only,
    * but each column will still be represented as an integer with `w = outDigits` bits.
    * The new matrices are put in `genMat`.
    * The algo is described in the document "latnetbuider notes".
    */
   public void leftMatrixScramble (RandomStream stream, int numBits) {
      int j, c, d; // dimension j, column c of original Cj, column d of new Cj.
      int jk;
      final long tworm1 = 1L << (numBits - 1); // 2^{numBits-1}
      final int wmr = outDigits - numBits;
      // If genMat contains the original gen. matrices, copy to originalMat.
      // Normally, we do this only once!
      if (originalMat == null) {  // This is only if `originalMat` was never created.
         // System.out.println("Copying genMat to originalMat \n");
         originalMat = genMat;
         genMat = new long[dim * numCols]; // Creates a new object, but only once.
      }
      for (d = 0; d < dim * numCols; d++) genMat[d] = 0;
      for (j = 0; j < dim; j++) {
         jk = j * numCols;        // Number of columns to skip
         for (c = 0; c < numRows; c++) {
            // colc is column c of L_j, which has numRows columns.
            long colc = (tworm1 + stream.nextLong(0, tworm1-1)) >> (c - wmr);
            // System.out.println("colc = " + colc + "\n");
            for (d = 0; d < numCols; d++)   // Column d for coordinate j.
               genMat[jk + d] ^= ((originalMat[jk + d] >> (outDigits-1-c)) & 1L) * colc;
         }
      }
      // numRows = numBits;   // The new generating matrices have r rows.
   }
   
   /**
    * By default, the matrices L_j have r = w rows.
    */
   public void leftMatrixScramble (RandomStream stream) {
      leftMatrixScramble (stream, outDigits);
   }

   // To be repaired with r instead of w rows....  
   public void iBinomialMatrixScramble(RandomStream stream) {
      int j, d; // Dimension j, subdiagonal d of M_j.
      final long allOnes = ((long)1 << outDigits) - 1; // outDigits ones.
      long lastRow; // Last row of M_j: w-1 random bits followed by 1.

      // If genMat is original generator matrices, copy it to originalMat.
      if (originalMat == null) {
         originalMat = genMat;
         genMat = new long[dim * numCols];
      }
      // Constructs the lower-triangular scrambling matrices M_j, w by w.
      // scrambleMat[j][l] contains row l of M_j.
      long[][] scrambleMat = new long[dim][outDigits];
      for (j = 0; j < dim; j++) {
         scrambleMat[j][0] = allOnes;
         lastRow = stream.nextLong(0, allOnes) | 1;
         for (d = 1; d < outDigits; d++)
            // Subdiagonal d contains either all ones or all zeros.
            if (((1 << d) & lastRow) == 0)
               scrambleMat[j][d] = 0;
            else
               scrambleMat[j][d] = (allOnes >> d) << d;
      }
      for (j = 0; j < dim; j++)
         leftMultiplyMat(j, scrambleMat[j]);
   }

   // To be repaired with r instead of w rows....  
   public void stripedMatrixScramble(RandomStream stream) {
      int j, d; // dimension j, subdiagonal d of M_j.

      // If genMat is original generator matrices, copy it to originalMat.
      if (originalMat == null) {
         originalMat = genMat;
         genMat = new long[dim * numCols];
      }
      // Constructs the lower-triangular scrambling matrix M, w by w,
      // filled with 1's. scrambleMat[d] contains subdiagonal d of M.
      long[] scrambleMat = new long[outDigits];
      final long allOnes = ((long)1 << outDigits) - 1; // outDigits ones.
      for (d = 0; d < outDigits; d++)
         scrambleMat[d] = (allOnes >> d) << d;
      for (j = 0; j < dim; j++)
         leftMultiplyMat(j, scrambleMat);
   }

   /*
    * public void leftMatrixScramble (RandomStream stream) { int j, l; // dimension
    * j, row l. int boundInt;
    * 
    * // If genMat contains the original gen. matrices, copy to originalMat. if
    * (originalMat == null) { originalMat = genMat; genMat = new int[dim *
    * numCols]; }
    * 
    * // Constructs the lower-triangular scrambling matrices M_j, w by w. //
    * scrambleMat[j][l] contains row l in a single integer (binary repres.) int[][]
    * scrambleMat = new int[dim][outDigits]; for (j = 0 ; j < dim; j++) { boundInt
    * = 0; for (l = 0; l < outDigits; l++) { boundInt += (1 << l); // Integer
    * repres. by string of l+1 ones. scrambleMat[j][l] = (stream.nextInt (0,
    * boundInt) | 1) << (outDigits-l-1); } }
    * 
    * // Multiply M_j by the generator matrix C_j for each j. for (j = 0; j < dim;
    * j++) leftMultiplyMat (j, scrambleMat[j]); }
    * 
    * public void iBinomialMatrixScramble (RandomStream stream) { int j, l; //
    * dimension j, row l of M_j. int allOnes;
    * 
    * // If genMat is original generator matrices, copy it to originalMat. if
    * (originalMat == null) { originalMat = genMat; genMat = new int[dim *
    * numCols]; }
    * 
    * // Constructs the lower-triangular scrambling matrices M_j, w by w. //
    * scrambleMat[j][l] contains row l of M_j. int[][] scrambleMat = new
    * int[dim][outDigits]; for (j = 0 ; j < dim; j++) { allOnes = ~0 >> (32 -
    * outDigits); // outDigits ones. scrambleMat[j][outDigits-1] = stream.nextInt
    * (0, allOnes) | 1; for (l = outDigits - 2; l >= 0; l--) scrambleMat[j][l] =
    * scrambleMat[j][l+1] << 1; }
    * 
    * for (j = 0; j < dim; j++) leftMultiplyMat (j, scrambleMat[j]); //
    * leftMultiplyMat (scrambleMat); }
    * 
    * public void stripedMatrixScramble (RandomStream stream) { int j, l; //
    * dimension j, row l of M_j. int allOnes;
    * 
    * // If genMat is original generator matrices, copy it to originalMat. if
    * (originalMat == null) { originalMat = genMat; genMat = new int[dim *
    * numCols]; }
    * 
    * // Constructs the lower-triangular scrambling matrix M, w by w, // filled
    * with 1's. scrambleMat[l] contains row l of M. int[] scrambleMat = new
    * int[outDigits]; allOnes = ~0 >> (32 - outDigits); // outDigits ones. for (l =
    * 0; l < outDigits; l++) scrambleMat[l] = (allOnes << (outDigits - 1 - l)) &
    * allOnes; for (j = 0; j < dim; j++) leftMultiplyMat (j, scrambleMat); }
    */

   public void rightMatrixScramble(RandomStream stream) {
      int j, c; // Dimension j, column c for new C_j.
      if (originalMat == null) {
         originalMat = genMat;
         genMat = new long[dim * numCols];
      }
      // Generate an upper triangular matrix for Faure-Tezuka right-scramble.
      // scrambleMat[c] contains column c of M.
      long[] scrambleMat = new long[outDigits];
      long boundLong = 0;
      for (c = 0; c < numCols; c++) {
         boundLong += (1 << c); // Integer repres. by string of c+1 ones.
         scrambleMat[c] = (1 | stream.nextLong(0, boundLong)) << (outDigits - c - 1);
      }
      // Right-multiply the generator matrices by the scrambling matrix.
      for (j = 0; j < dim; j++)
         rightMultiplyMat(j, scrambleMat);
   }




   /**
    * Generate a vector of `numBits <= 63` random bits using the random stream
    * `stream`.  These `numBits` bits will be the most significant ones in the 63-bit integer.
    */
   private long randomBitVectorLong(RandomStream stream, int numBits) {
      if (numBits < 1)
         throw new IllegalArgumentException("numBits must be >= 1");
      if (numBits > 63)
         throw new IllegalArgumentException("numBits must be <= 63");
      long maxj = (1L << numBits) - 1;
      return stream.nextLong(0, maxj) << (63 - numBits);
   }

   /**
    * Same as @link nestedUniformScramble(RandomStream, double[][], int)
    * nestedUniformScramble(stream, output, 0) @endlink.
    */
   // public void nestedUniformScramble(RandomStream stream, double[][] output) {
   //    nestedUniformScramble(stream, output, 0);
   // }

//    public void nestedUniformScramble(RandomStream stream, double[][] output, int numBits) {
//       nestedUniformScramble64(stream, output, numBits);
//    }

  public void nestedUniformScramble(RandomStream stream, double[][] output, int numBits) {
      assert output.length == numPoints;
      assert output.length > 0;
      assert output[0].length == dim;
      assert outDigits >= 31;
      assert outDigits <= 62;

      if (numBits == 0)
         numBits = 18;
      if (numBits != 18)
         throw new IllegalArgumentException("numBits must be 18");

      double localNormFactor = 1.0 / Math.abs((double) (1L << outDigits));

      int[] poslist = new int[2 * numPoints];
      long[] bvlist = new long[2 * numPoints];
      int[] counts = new int[256];
      int[] binpos = new int[256];

      for (int j = 0; j < dim; ++j) {
         bvlist[0] = 0;
         poslist[0] = 0;

         for (int i = 1; i < numPoints; i++) {
            int pos = 0;
            int bv = 1;

            while ((i & bv) == 0) {
               pos++;
               bv <<= 1;
            }

            bvlist[i] = bvlist[i - 1]
                  ^ (genMat[j * numCols + pos] >>> (outDigits - 31));
            poslist[i] = i;
         }

         for (int b = 0; b < 4; b++) {
            for (int i = 0; i < 256; i++)
               counts[i] = 0;

            int m = (b % 2) * numPoints;
            int bb = 8 * b;
            long bv = 0xffL << bb;

            for (int i = 0; i < numPoints; i++)
               counts[(int) ((bvlist[m + i] & bv) >>> bb)]++;

            binpos[0] = (1 - b % 2) * numPoints;

            for (int i = 0; i < 255; i++)
               binpos[i + 1] = binpos[i] + counts[i];

            for (int i = 0; i < numPoints; i++) {
               int pos = (int) ((bvlist[m + i] & bv) >>> bb);
               int k = binpos[pos]++;

               bvlist[k] = bvlist[m + i];
               poslist[k] = poslist[m + i];
            }
         }

         // int[]   firstTable = new int[64];// up to 6 levels
         // int[][] secondTables = new int[64][64]; // up to 12 levels
         // int[][] thirdTables = new int[4096][64]; // up to 18 levels

         // buildNUS6Table(stream.nextBitsLong(63), firstTable);

         // for (int prefix = 0; prefix < 64; prefix++)
         //    buildNUS6Table(stream.nextBitsLong(63), secondTables[prefix]);
         
         // for (int prefix = 0; prefix < 4096; prefix++)
         //    buildNUS6Table(stream.nextBitsLong(63), thirdTables[prefix]);

         // long prefixMask = 0x3ffffL << 13;
         

         // for (int i = 0; i < numPoints; i++) {
         //    int first6 = (int) ((bvlist[i] >>> 25) & 0x3fL);
         //    int second6 = (int) ((bvlist[i] >>> 19) & 0x3fL);
         //    int third6 = (int) ((bvlist[i] >>> 13) & 0x3fL);

         //    int prefix12 = (first6 << 6) | second6; // to use in the third table

         //    int scrambled18 =
         //          (firstTable[first6] << 12)
         //          | (secondTables[first6][second6] << 6)
         //          | thirdTables[prefix12][third6];

         //    long scrambled =
         //          (bvlist[i] & ~prefixMask)
         //          | ((long) scrambled18 << 13);

         //    long scrambledL = scrambled << (outDigits - 31);

         //    output[poslist[i]][j] =
         //          scrambledL * localNormFactor + EpsilonHalf;
         // }

         long firstPermutations = stream.nextBitsLong(63);
         long secondPermutations = 0L;
         long thirdPermutations = 0L;

         int previousFirst6 = -1;
         int previousPrefix12 = -1;
         int previousPrefix18 = -1;

         int scrambledFirst6 = 0;
         int scrambledSecond6 = 0;
         int scrambledThird6 = 0;

         long prefixMask = 0x3ffffL << 13;

         for (int i = 0; i < numPoints; i++) {
            int first6 = (int) ((bvlist[i] >>> 25) & 0x3fL);
            int second6 = (int) ((bvlist[i] >>> 19) & 0x3fL);
            int third6 = (int) ((bvlist[i] >>> 13) & 0x3fL);

            int prefix12 = (first6 << 6) | second6;
            int prefix18 = (prefix12 << 6) | third6;

            if (first6 != previousFirst6) {
               previousFirst6 = first6;

               secondPermutations = stream.nextBitsLong(63);
               scrambledFirst6 =
                     scrambleNUS6Value(firstPermutations, first6);
            }

            if (prefix12 != previousPrefix12) {
               previousPrefix12 = prefix12;

               thirdPermutations = stream.nextBitsLong(63);
               scrambledSecond6 =
                     scrambleNUS6Value(secondPermutations, second6);
            }

            if (prefix18 != previousPrefix18) {
               previousPrefix18 = prefix18;

               scrambledThird6 =
                     scrambleNUS6Value(thirdPermutations, third6);
            }

            int scrambled18 =
                  (scrambledFirst6 << 12)
                  | (scrambledSecond6 << 6)
                  | scrambledThird6;

            long scrambled =
                  (bvlist[i] & ~prefixMask)
                  | ((long) scrambled18 << 13);

            long scrambledL = scrambled << (outDigits - 31);

            output[poslist[i]][j] =
                  scrambledL * localNormFactor + EpsilonHalf;
         }
      }
   }

   private int scrambleNUS6Value(long permutations, int value) {
      int prefix = 0;
      int scrambled = 0;

      for (int level = 0; level < 6; level++) {
         int inputBit = (value >>> (5 - level)) & 1;
         int node = (1 << level) - 1 + prefix;
         int permutationBit =
               (int) ((permutations >>> node) & 1L);

         scrambled =
               (scrambled << 1)
               | (inputBit ^ permutationBit);

         prefix = (prefix << 1) | inputBit;
      }

      return scrambled;
   }
   /**
    * Builds the permutation table for all possible 6-bit input values.
    *
    * @param permutations   random vector containing the 63 permutation bits
    * @param table          stores each 6-bit input value and its corresponding scrambled value
    */
  private void buildNUS6Table(long permutations, int[] table) {
      // loop over all possible values of 6 the digits bloc that this coordinate can have
      // this can be any bloc (1to6, 7 to 12, ...)
      for (int value = 0; value < 64; value++) {
         int prefix = 0;//Store used bits to select the correct tree node
         int scrambled = 0;
         //loop over the six digits of this bloc
         for (int level = 0; level < 6; level++) {
            int inputBit = (value >>> (5 - level)) & 1;// read from the left
            int node = (1 << level) - 1 + prefix; // current node: level 1 starts at 0,2 starts at 1, 3 at 7 ,2*l - 1 + position at current level 
            int permutationBit =
                  (int) ((permutations >>> node) & 1L); // bitPermutation at this node

            scrambled =
                  (scrambled << 1)
                  | (inputBit ^ permutationBit);// build the scrambeled 6 dg

            prefix = (prefix << 1) | inputBit;// append input bit the prefix
         }

         table[value] = scrambled;
      }
   }
   
   // -----------------------------------------------------------------------
   private void ScrambleError(String method) {
      throw new UnsupportedOperationException(
            PrintfFormat.NEWLINE + "  " + method + " is not implemented for a DigitalNetBase2");
   }

   public void leftMatrixScrambleDiag(RandomStream stream) {
      ScrambleError("leftMatrixScrambleDiag");
   }

   public void leftMatrixScrambleFaurePermut(RandomStream stream, int sb) {
      ScrambleError("leftMatrixScrambleFaurePermut");
   }

   public void leftMatrixScrambleFaurePermutDiag(RandomStream stream, int sb) {
      ScrambleError("leftMatrixScrambleFaurePermutDiag");
   }

   public void leftMatrixScrambleFaurePermutAll(RandomStream stream, int sb) {
      ScrambleError("leftMatrixScrambleFaurePermutAll");
   }

   public void iBinomialMatrixScrambleFaurePermut(RandomStream stream, int sb) {
      ScrambleError("iBinomialMatrixScrambleFaurePermut");
   }

   public void iBinomialMatrixScrambleFaurePermutDiag(RandomStream stream, int sb) {
      ScrambleError("iBinomialMatrixScrambleFaurePermutDiag");
   }

   public void iBinomialMatrixScrambleFaurePermutAll(RandomStream stream, int sb) {
      ScrambleError("iBinomialMatrixScrambleFaurePermutAll");
   }

   public void stripedMatrixScrambleFaurePermutAll(RandomStream stream, int sb) {
      ScrambleError("stripedMatrixScrambleFaurePermutAll");
   }

   /**
    * Interlaces the points from a digital net.
    *
    * *****  This should probably be in `CachedPointSet`.  ***** 
    * This is useful for interlacing after NUS, since NUS returns the points. For
    * other use cases, @link matrixInterlace()@endlink should be preferred.
    *
    * @param points           Array that stores the non-interlaced points as
    *                         integers. The size of its first dimension must be
    *                         getNumPoints() and the size of its second dimension
    *                         must be getDimension().
    * @param interlacedPoints Output array that will store the interlaced points.
    *                         The size of its first dimension must be
    *                         getNumPoints() and the size of its second dimension
    *                         must be getDimension() / getInterlacing().
    */
   public void outputInterlace(long[][] points, double[][] interlacedPoints) {
      assert points.length == numPoints;
      assert points.length > 0;
      assert points[0].length == dim;

      assert interlacedPoints.length == numPoints;
      assert interlacedPoints.length > 0;
      assert interlacedPoints[0].length * interlacing == dim;

      double longNormFactor = 1 / (Math.pow(2, 63));

      for (int i = 0; i < numPoints; i++) {
         for (int j = 0; j < dim / interlacing; ++j) {
            long result = 0;
            for (int idx = 0; idx < interlacing; ++idx) {
               int coord = j * interlacing + idx;
               int interlaced_pos = 62 - idx;
               int original_pos = 30;
               int mask = 1 << original_pos;
               while (interlaced_pos >= 0 && original_pos >= 0) {
                  assert interlaced_pos >= original_pos;
                  result += (((long) (points[i][coord] & mask)) << (interlaced_pos - original_pos));
                  interlaced_pos -= interlacing;
                  original_pos -= 1;
                  mask >>= 1;
               }
            }
            interlacedPoints[i][j] = result * longNormFactor + EpsilonHalf;
         }
      }
   }

   /**
    * Interlaces the generating matrices of this digital net and returns the new
    * interlaced `DigitalNetBase2`.
    *
    * This function returns a new digital net, whose dimension equals
    * getDimension() / getInterlacing(), and whose generating matrices are
    * interlaced.
    */
   public DigitalNetBase2 matrixInterlace(int interlace, int newDim) {
      assert interlace * newDim <= dim;     
      DigitalNetBase2 result = new DigitalNetBase2();  // Creates a new interlaced net object.
      result.dim = newDim;
      result.numPoints = numPoints;
      result.outDigits = outDigits;
      result.normFactor = normFactor;
      result.numCols = numCols;
      result.numRows = Math.min(outDigits, numRows * interlace);

      long[][][] nonInterlacedMatrices = generatorMatricesToBitFormat();
      long[][][] interlacedMatrices = new long[result.dim][result.numRows][result.numCols];
      int r, j; // Row r, dimension j.
      for (j = 0; j < result.dim; ++j) {
         for (r = 0; r < result.numRows; ++r) {
            // This copies all the columns for row r.
            interlacedMatrices[j][r] = nonInterlacedMatrices[j * interlace + r % interlace][r / interlace];
         }
      }
      result.generatorMatricesFromBitFormat(interlacedMatrices);
      return result;
   }
   

   /**
    * Interlaces the generating matrices of this digital net and returns the new
    * interlaced `DigitalNetBase2`.
    *
    * This function returns a new digital net, whose dimension equals
    * getDimension() / getInterlacing(), and whose generating matrices are
    * interlaced.
    */
   public DigitalNetBase2 matrixInterlace() {
      return matrixInterlace(interlacing, dim / interlacing);
   }
      

   // *******************************************************************
   protected class DigitalNetBase2Iterator extends DigitalNetIterator {

      // Coordinates of the current point stored (cached) as integers.
      // Initially contains zeros, because first point is always zero.
      // Incorporates the random digital shift, except for the first point.
      // There is one more dimension for the points because of the
      // shift iterators children of DigitalNetBase2Iterator.
      // dimS = dim, except for the shift iterator children where
      // dimS = dim + 1.
      protected int dimS;
      protected long[] cachedCurPoint;   // Redefined: Coords of the current point,

      public DigitalNetBase2Iterator() {
         super();
         EpsilonHalf = 0.5 / Num.TWOEXP[outDigits];
         cachedCurPoint = new long[dim + 1];
         dimS = dim;
         init2();
      }

      // Redefining this method is necessary to overload the init() of DigitalNetIterator.
      public void init() {} 

      public void init2() { // See constructor
         resetCurPointIndex();
      }

      // We want to avoid generating 0 or 1
      public double nextDouble() {
         return nextCoordinate();
      }

      public double nextCoordinate() {
         if (curPointIndex >= numPoints || curCoordIndex >= dimS)
            outOfBounds();
         long x = cachedCurPoint[curCoordIndex++];
         if (streamIRB != null)
            x = x ^ streamIRB.nextLong(0, (1L << outDigits-numCols)-1);
         if (digitalShift == null)
            return x * normFactor;
         else
            return x * normFactor + EpsilonHalf;
      }

      protected void addShiftToCache() {
         if (digitalShift == null)
            for (int j = 0; j < dim; j++)
               cachedCurPoint[j] = 0;
         else {
            if (dimShift < dimS)
               addRandomShift(dimShift, dimS, shiftStream);
            for (int j = 0; j < dim; j++)
               cachedCurPoint[j] = digitalShift[j];
         }
      }

      public void resetCurPointIndex() {
         addShiftToCache();
         curPointIndex = 0;
         curCoordIndex = 0;
      }

      public void setCurPointIndex(int i) {
         if (i == 0) {
            resetCurPointIndex();
            return;
         }
         // Out of order computation, must recompute the cached current
         // point from scratch.
         curPointIndex = i;
         curCoordIndex = 0;
         addShiftToCache();

         int j;
         int grayCode = i ^ (i >> 1);
         int pos = 0; // Position of the bit that is examined.
         while ((grayCode >> pos) != 0) {
            if (((grayCode >> pos) & 1) != 0)
               for (j = 0; j < dim; j++)
                  cachedCurPoint[j] ^= genMat[j * numCols + pos];
            pos++;
         }
      }

      public int resetToNextPoint() {
         int pos = 0; // Will be position of change in Gray code,
                      // = pos. of first 0 in binary code of point index.
         while (((curPointIndex >> pos) & 1) != 0)
            pos++;
         if (pos < numCols) {
            for (int j = 0; j < dim; j++)
               cachedCurPoint[j] ^= genMat[j * numCols + pos];
         }
         curCoordIndex = 0;
         return ++curPointIndex;
      }

      public int nextPoint(double p[], int d) {
         if (curPointIndex >= numPoints || d > dimS)
            outOfBounds();
         for (int j = 0; j < d; j++) {
            long x = cachedCurPoint[j];
            if (streamIRB != null)
               x = x ^ streamIRB.nextLong(0, (1L << outDigits-numCols)-1);
            if (digitalShift == null)
               p[j] = x * normFactor;
            else
               p[j] = x * normFactor + EpsilonHalf;
         }
         return resetToNextPoint();
      }
   }

   // *******************************************************************
   protected class DigitalNetBase2IteratorNoGray extends DigitalNetBase2Iterator {

      // Same as DigitalNetBase2Iterator,
      // except that the Gray code is not used.

      public DigitalNetBase2IteratorNoGray() {
         super();
      }

      public void setCurPointIndex(int i) {
         if (i == 0) {
            resetCurPointIndex();
            return;
         }
         // Out of order computation, must recompute the cached current
         // point from scratch.
         curPointIndex = i;
         curCoordIndex = 0;
         addShiftToCache();
         int pos = 0; // Position of the bit that is examined.
         while ((i >> pos) != 0) {
            if ((((i >> pos) & 1) != 0) && (pos < numCols)) {
               for (int j = 0; j < dim; j++)
                  cachedCurPoint[j] ^= genMat[j * numCols + pos];
            }
            pos++;
         }
      }

      public int resetToNextPoint() {
         // Contains the bits of i that changed.
         if (curPointIndex + 1 >= numPoints)
            return ++curPointIndex;
         int diff = curPointIndex ^ (curPointIndex + 1);
         int pos = 0; // Position of the bit that is examined.
         while ((diff >> pos) != 0) {
            if ((((diff >> pos) & 1) != 0) && (pos < numCols)) {
               for (int j = 0; j < dim; j++)
                  cachedCurPoint[j] ^= genMat[j * numCols + pos];
            }
            pos++;
         }
         curCoordIndex = 0;
         return ++curPointIndex;
      }

   }
   

   // *******************************************************************
   //                  DOES NOT WORK
   // 
   // This was an attempt to implement an iterator for when we apply NUS and do not
   // want to store all the points in a cache point set.  
   // Unfortunately, this does not work, because in the correct implementation of NUS,
   // the points are permuted in a different order for their different coordinates.
   //    
   protected class DigitalNetBase2IteratorNUSWrong extends DigitalNetBase2Iterator {

      // This was  a version of the iterator used for when we apply NUS and do not
      // want to store all the points in a cache point set. 
      // Here, the points are randomized by the iterator, using `streamNUS`.

      protected double[] cachedCurPointD;   // Redefined: Coords of the current point,
      protected long[] bv;
      // RandomStream streamIterNUS;

      public DigitalNetBase2IteratorNUSWrong(RandomStream stream) {
         super();     
         // System.out.println("Allo IteratorNUS \n" + stream.toString());
         streamNUS = stream; 
         initNUS();
      }

      // Redefining this method is necessary to overload the init() of DigitalNetIterator.
      public void init2() {} 

      public void initNUS() { // See constructor
         bv = new long[dim+1];
         cachedCurPointD = new double[dim + 1];
         // System.out.println("initNUS: \n " + streamIterNUS.toString());
         //  resetCurPointIndex();    // Must call `randomize` before doing this.....
      }

      public double nextCoordinate() {
         // System.out.println("nextCoordinate, curCoordIndex = " + curCoordIndex + ", "
         //      + "value = " + cachedCurPointD[curCoordIndex]);
         if (curPointIndex >= numPoints || curCoordIndex >= dim)
            outOfBounds();
         return cachedCurPointD[curCoordIndex++];
      }

      public void resetCurPointIndex() {
         // System.out.println("resetCurPointIndex, dim = " + dim);
         // System.out.println(streamIterNUS.toString());
         for (int j = 0; j < dim; j++) {
            bv[j] = (streamNUS.nextLong(0, (1L << numBitsNUS)-1) << (outDigits - numBitsNUS));
            long bvlistL = (bvlistNUS[poslistInvNUS[0][j]][j]) << (outDigits - 31);
            // System.out.println("bvlistL = " + bvlistL);
            // System.out.println("bv[j] = " + bv[j]);
            cachedCurPointD[j] = (bvlistL ^ bv[j]) * normFactorNUS + EpsilonHalf; 
            // System.out.println("cachedCurPointD[j] = " + cachedCurPointD[j]);
         }
         curPointIndex = 0;
         curCoordIndex = 0;
      }

      public void setCurPointIndex(int i) {
         if (i == 0)
            resetCurPointIndex();
         else
            throw new IllegalArgumentException(" setCurPointIndex(i) for i > 0 not allowed for NUS iterator.");
      }

      public int resetToNextPoint() {
         curPointIndex++;
         if (curPointIndex >= numPoints)
            return curPointIndex;
         // System.out.println("\nStart resetToNextPoint, curPointIndex = " + curPointIndex + ", dim = " + dim);
         for (int j = 0; j < dim; j++) {
            // The following does not work because when we apply `poslistInv`, we no longer have
            // successive coordinates.   ********
            long bv2 = (bvlistNUS[poslistInvNUS[curPointIndex - 1][j]][j]) << (outDigits - 31);
            long bvlistL = (bvlistNUS[poslistInvNUS[curPointIndex][j]][j]) << (outDigits - 31);
            bv2 ^= bvlistL;
            // System.out.println("bv2 = " + Long.toBinaryString(bv2));
            bv2 = (streamNUS.nextLong(0, (1L << numBitsNUS)-1) << (outDigits - numBitsNUS))
                  & ((1L << (long) Num.log2((double) bv2)) - 1);
            // System.out.println("bv2 = " + Long.toBinaryString(bv2));
            bv[j] ^= bv2;
            // The following is incorrect, because these dim coordinates belong to different points!!!
            cachedCurPointD[j] = (bvlistL ^ bv[j]) * normFactorNUS + EpsilonHalf;        
         }
         curCoordIndex = 0;
         // System.out.println("Exit resetToNextPoint, curPointIndex = " + curPointIndex);
         return curPointIndex;
      }

      public int nextPoint(double p[], int d) {
         if (curPointIndex >= numPoints || d > dim)
            outOfBounds();
         for (int j = 0; j < d; j++)
            p[j] = cachedCurPointD[j];
         return resetToNextPoint();
      }
   }

}
